
info:
  title: Basit Giriş API
  description: 'Bu API, ödev projesi için oluşturulmuş basit bir kullanıcı doğrulama
    servisini

    temsil eder. ''admin'' ve ''12345'' kred bilgileriyle çalışır.'
  version: 1.0.0
servers:
- url: http://localhost:8000
  description: Yerel Geliştirme Sunucusu
paths:
  /login:
    post:
      summary: Kullanıcı girişi yapar
      description: Kullanıcı adı ve şifre alarak sistemi doğrulamaya çalışır.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                kullanici_adi:
                  type: string
                  description: Sisteme kayıtlı kullanıcı adı
                  example: admin
                sifre:
                  type: string
                  description: Kullanıcıya ait şifre
                  example: '12345'
              required:
              - kullanici_adi
              - sifre
      responses:
        '200':
          description: Giriş Başarılı
          content:
            application/json:
              schema:
                type: object
                properties:
                  durum:
                    type: string
                    example: basarili
                  mesaj:
                    type: string
                    example: Giriş Başarılı
        '400':
          description: Hatalı istek (JSON formatı veya eksik alanlar)
          content:
            application/json:
              schema:
                type: object
                properties:
                  durum:
                    type: string
                    example: hata
                  mesaj:
                    type: string
                    example: Eksik bilgi. 'kullanici_adi' ve 'sifre' alanları zorunludur.
        '401':
          description: Hatalı kullanıcı adı veya şifre
          content:
            application/json:
              schema:
                type: object
                properties:
                  durum:
                    type: string
                    example: hata
                  mesaj:
                    type: string
                    example: Hatalı Bilgi Girdiniz
